DEBUG = True
INSTALLED_APPS.append('django_extensions')
ALLOWED_HOSTS = ['*']

del SECURE_SSL_REDIRECT
del SESSION_COOKIE_SECURE
del CSRF_COOKIE_SECURE
del SECURE_HSTS_SECONDS
del SECURE_HSTS_INCLUDE_SUBDOMAINS
del SECURE_HSTS_PRELOAD

INTERNAL_IPS = ['127.0.0.1']
